// src/infrastructure/capability/capability.decorators.ts
// Re-export from types layer — modules and infrastructure both use @app-types/common/capability-decorators
export {
  CAPABILITY_EVENT_SUBSCRIBER_DISCOVERABLE,
  CAPABILITY_EVENT_SUBSCRIBER_METADATA_KEY,
  CAPABILITY_HEALTH_CHECK_DISCOVERABLE,
  CAPABILITY_HEALTH_CHECK_METADATA_KEY,
  CAPABILITY_MANIFEST_DISCOVERABLE,
  CAPABILITY_MANIFEST_METADATA_KEY,
  CAPABILITY_OPERATION_HANDLER_DISCOVERABLE,
  CAPABILITY_OPERATION_HANDLER_METADATA_KEY,
  CAPABILITY_PROVIDER_BINDING_DISCOVERABLE,
  CAPABILITY_PROVIDER_BINDING_METADATA_KEY,
  CAPABILITY_QUEUE_BINDING_DISCOVERABLE,
  CAPABILITY_QUEUE_BINDING_METADATA_KEY,
  CAPABILITY_SESSION_AUTHORITY_SCOPE_AUTHORIZER_DISCOVERABLE,
  CAPABILITY_SESSION_AUTHORITY_SCOPE_AUTHORIZER_METADATA_KEY,
  CAPABILITY_SESSION_AUTHORITY_SUMMARY_RESOLVER_DISCOVERABLE,
  CAPABILITY_SESSION_AUTHORITY_SUMMARY_RESOLVER_METADATA_KEY,
  CAPABILITY_SESSION_IDENTITY_RESOLVER_DISCOVERABLE,
  CAPABILITY_SESSION_IDENTITY_RESOLVER_METADATA_KEY,
  CapabilityEventSubscriberProvider,
  CapabilityHealthCheckProvider,
  CapabilityManifestProvider,
  CapabilityOperationHandlerProvider,
  CapabilityProviderBindingProvider,
  CapabilityQueueBindingProvider,
  CapabilitySessionAuthorityScopeAuthorizerProvider,
  CapabilitySessionAuthoritySummaryResolverProvider,
  CapabilitySessionIdentityResolverProvider,
  isCapabilityHealthCheck,
  type CapabilityEventSubscriberMetadata,
  type CapabilityHealthCheckMetadata,
  type CapabilityOperationHandlerMetadata,
  type CapabilityProviderBindingMetadata,
  type CapabilityQueueBindingMetadata,
  type CapabilitySessionAuthorityScopeAuthorizerMetadata,
  type CapabilitySessionAuthoritySummaryResolverMetadata,
  type CapabilitySessionIdentityResolverMetadata,
} from '@app-types/common/capability-decorators';
